import { Manrope } from 'next/font/google'
import './globals.css'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Voyatek',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex justify-center max-w-[1500px]'>{children}</body>
    </html>
  )
}
export default RootLayout;
