import { Syne } from 'next/font/google'
import './globals.css'

const syne = Syne({ subsets: ['latin'] })

export const metadata = {
  title: 'GoPaddi',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${syne.className} flex justify-center max-w-[1500px]`}>{children}</body>
    </html>
  )
}
export default RootLayout;
